### PR TITLE
Feature/adding optional stsarn

### PR DESCRIPTION
**Pull request by pmdumuid**
This enables a STS ARN textbox and some build info updates.

The STS ARN can be used to obtain secondary keys.

Essentially this enables the use of STS to assume roles to access the simple db.  Roles can be used as a means of "elevating privileges", and also cross-account simpleDB access (my use-case where I have an account for users, and roles in other accounts that let the "users" account access the other accounts.)

### CODE REVIEW

**Comment by Reggino** [comment]
Sorry for the late reply, this looks awesome! 

Thanks!

**Comment by pmdumuid** [comment]
Thanks,

Will you be-rebuilding / publishing to the extension?  I was wondering
about creating my own extension in the play store to share this with my
colleagues.  But if you push an new build to the store that'd be great!

**Comment by Reggino** [comment]
I'll try and push a new build today ;-)

**Comment by Reggino** [comment]
An updated version (2.0.8) has just been released, thanks

**Pull request merged**
